// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAny1d2MNPQmsrJRUyhubeG4LFZ6jlt4',
    appId: '1:1005268516345:web:12e2025e2a54868b375128',
    messagingSenderId: '1005268516345',
    projectId: 'cibra-ab4d6',
    authDomain: 'cibra-ab4d6.firebaseapp.com',
    storageBucket: 'cibra-ab4d6.firebasestorage.app',
    measurementId: 'G-BHF0FFPYCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfT2or_qnE0bnQmAEbSEWIQsLBXdjY8HU',
    appId: '1:1005268516345:android:f90a18070e44341e375128',
    messagingSenderId: '1005268516345',
    projectId: 'cibra-ab4d6',
    storageBucket: 'cibra-ab4d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3dKfKsaqIYZtvLw_RKSdHT84tT9uB38',
    appId: '1:1005268516345:ios:414c5bfea5d60a0f375128',
    messagingSenderId: '1005268516345',
    projectId: 'cibra-ab4d6',
    storageBucket: 'cibra-ab4d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3dKfKsaqIYZtvLw_RKSdHT84tT9uB38',
    appId: '1:1005268516345:ios:414c5bfea5d60a0f375128',
    messagingSenderId: '1005268516345',
    projectId: 'cibra-ab4d6',
    storageBucket: 'cibra-ab4d6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAAny1d2MNPQmsrJRUyhubeG4LFZ6jlt4',
    appId: '1:1005268516345:web:0de2f9a02387dfa2375128',
    messagingSenderId: '1005268516345',
    projectId: 'cibra-ab4d6',
    authDomain: 'cibra-ab4d6.firebaseapp.com',
    storageBucket: 'cibra-ab4d6.firebasestorage.app',
    measurementId: 'G-FG23TG4F32',
  );
}
